### ISSUE TITLE
Push Cannons still shoot when submerged

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#38]
Push Cannons still shoot when submerged in water/trenches, and their fireballs can be seen outside of the level boundary on the right side. Also, the sound of the cannon fire can be heard when near the out-of-bounds fireball.

**Comment by ALEXM99999** [comment]
Fixed on commit e8ca6d49. Btw, this was basically a vanilla bug. When a box is submerged it's not set to dead but instead it's sent to coordinates X 101. Wonderland plus however, doesn't allocate a 101x101 array on every level regardless of it's size, but it allocates exactly as much space as needed depending on the level. As a result boxes are sent to max width on wonderland plus which cause you to see the fireballs if you are at the rightmost part of the level even if a level is 20x20 level, because cannon is on width 21, while in vanilla it would be in 101. If you create a 99x99 level in vanilla you will see it happens there too but of course 99x99 levels are very rare so apparently nobody noticed it before.
