### ISSUE TITLE
Most submersible objects on certain bridge types will submerge at start of level

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WPlusIssues#71]
Edit: Forgot to mention that this bug makes the level "Coins For Better and Worse" impossible.
I decided to take a video of this particular issue:

https://user-images.githubusercontent.com/11260985/197938740-19321a21-1f96-4793-a1c9-08519456bc04.mp4

**Comment by ALEXM99999** [comment]
Yeah, boxes that can enter a liquid type and not be destroyed on that particular liquid will submerge on level startup if they are placed on a liquid tile. Problem here is that because of the change of some tiles to objects, the game doesn't check if there is a bridge (or also a transporter) so boxes on bridges that are placed above the liquid will still be submerged. I will fix this bug soon. thanks!

**Comment by ALEXM99999** [comment]
Fixed on commit c0408f12.
